<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>WordWebCMS</RootNamespace>
    <AssemblyName>WordWebCMS</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="*.aspx.cs" />
    <Compile Remove="*.aspx.designer.cs" />
    <Compile Remove="AJAX.ashx.cs" />
    <None Include="*.aspx" />
    <None Include="*.aspx.cs" />
    <None Include="*.aspx.designer.cs" />
    <None Include="AJAX.ashx" />
    <None Include="AJAX.ashx.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MySqlConnector" Version="2.3.7" />
    <PackageReference Include="Markdig" Version="0.37.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="LineputScript">
      <HintPath>lib/LineputScript.dll</HintPath>
      <Aliases>global,LinePutScriptCore</Aliases>
    </Reference>
    <Reference Include="LinePutScript.Core">
      <HintPath>lib/LineputScript.dll</HintPath>
    </Reference>
    <Reference Include="LinePutScript.SQLHelper.Core">
      <HintPath>lib/LinePutScript.SQLHelper.Core.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Include="lib\**\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
